#org: RamNellutla
app: cryptoTracker
service: flask-api

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getListings:
    handler: wsgi_handler.handler
    events:
      - http 'GET /listings/{proxy+}'
  getGlobalMetrics:
    handler: wsgi_handler.handler
    events:
      - http 'GET /globals/{proxy+}'

custom:
  wsgi:
    app: app.app
    pythonBin: python3 # Some systems with Python3 may require this
    packRequirements: false

  pythonRequirements:
    dockerizePip: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
